### ISSUE TITLE
develNext build failed

### ISSUE THREAD

**Issue by ousmanesene** [jphp-compiler/develnext#1]
Hi,

I'm really enthusiastic with your project. There are a lot of things i want to do with Jphp.

When will be the v0.7.2 release date?

Have a nice day.

**Comment by dim-s** [comment]
DevelNext is a special IDE for beginners, it based on JavaFX and JPHP, for creating gui programs. Now the project has only russian localization and based on jphp-0.7.2 that is SNAPSHOT and not released. 

You can read about the project here: http://community.develstudio.ru/showthread.php/9857-DevelNext-%D0%91%D0%BB%D0%BE%D0%B3-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8?p=113330&viewfull=1#post113330

With google translate: https://translate.google.ru/translate?hl=ru&sl=ru&tl=en&u=http%3A%2F%2Fcommunity.develstudio.ru%2Fshowthread.php%2F9857-DevelNext-%D0%91%D0%BB%D0%BE%D0%B3-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%3Fp%3D113330%26viewfull%3D1%23post113330

You can find nightly builds there.
