### ISSUE TITLE
Mac OS X Communications error OS_xpc_error: <error: 0x7fff7809db60>

### ISSUE THREAD

**Issue by hbody** [jphp-compiler/develnext#10]
При создании проекта на Mac OS X среда полностью зависает, а в терминале спустя некоторое время появляется следующая ошибка:

      INFO [ide.project.Project] (2016-01-25 20:27:01) Project is saved.
      INFO [ide.editors.AbstractEditor] (2016-01-25 20:27:02) Open editor for: /Users/wielski/Documents/DevelNext/Projects/wURL/src/.forms/MainForm.fxml
      INFO [ide.editors.FormEditor] (2016-01-25 20:27:02) Start refresh
      INFO [ide.editors.FormEditor] (2016-01-25 20:27:02) Finish refresh
      2016-01-25 20:27:05.856 java[21747:398194] Communications error: <OS_xpc_error: <error: 0x7fff7809db60> { count = 1, contents =
      	"XPCErrorDescription" => <string: 0x7fff7809dfa8> { length = 22, contents = "Connection interrupted" }
      }>

**Comment by dim-s** [comment]
К сожалению у меня нет MacOS, чтобы тестировать на нем. Давно вы пользуетесь develnext на MacOS? Раньше было такое или впервые запустили?

**Comment by hbody** [comment]
@dim-s Одни из первых сборок стартовали нормально. После чего не тестировал, ожидая стабильных версий. Решил проверить новую сборку недели полторы назад, но к сожалению постоянно выскакивает эта ошибка, и студия зависает. Перепробовал все, не найдя решения решил отписать тут.

**Comment by dim-s** [comment]
@hbody вы патч последний ставили?

**Comment by hbody** [comment]
Да.

**Comment by hbody** [comment]
![2016-02-08 03 36 05](https://cloud.githubusercontent.com/assets/16509249/12876185/339542e8-ce15-11e5-99df-2216c5a974b0.png)
Рапорт с последней версии (с установленным патчем).
Виснет намертво на шаге обновления ide.editors.FormEditor

**Comment by tibezh** [comment]
Увы у меня совсем версия под Mac(10.11.5) не запускается =(
Было бы неплохо сделать отдельный инсталятор для мак.
