### ISSUE TITLE
Компиляция всего проекта в байткод

### ISSUE THREAD

**Issue by dim-s** [jphp-compiler/develnext#14]
Компиляция проекта в байткод (в файлы phb), исходники надо удалять.

**Comment by MrEldar** [comment]
Какие ещё исходники?

**Comment by MrEldar** [comment]
Почему закрыто?!

**Comment by dim-s** [comment]
@MrEldar Это означает, что реализовано.

**Comment by MrEldar** [comment]
@dim-s Уже будет в следующей версии?

**Comment by MrEldar** [comment]
@dim-s Что значит 	Fix #20, close #14?

**Comment by dim-s** [comment]
@MrEldar Fix - это для багов, close это закрыть issue для фич.
