### ISSUE TITLE
doShowing & doShow start faster than doConstruct

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#169]
doShowing & doShow start faster than doConstruct
![image](https://user-images.githubusercontent.com/17342159/27793446-b9fed752-6006-11e7-9b6e-776a18a22baf.png)

**Comment by dim-s** [comment]
Событие загрузка формы и вообще загрузка подразумевает, что компонент полностью загружен для работы с ним.

**Comment by artemirq** [comment]
@dim-s, В моем проекте нужно было сделать инициализацию объектов при создании формы. Но т.к. у меня еще логика в doShowing,   doConstruct не подходит. Может запилишь еще одно действие, doConstructing?

**Comment by dim-s** [comment]
@artemirq 

У AbstractForm есть метод init(), который выполняется при создании самого объекта формы, просто объяви метод init() в классе формы:

```php
class MainForm extends AbstractForm {
    function init() {
            // твой код
    }
}
```

**Comment by artemirq** [comment]
@dim-s, Ух-ты, спасибо. Не знал о такой штуке. Не плохо бы задокументировать :)
