### ISSUE TITLE
UXMedia не работает с ресурсными файлами

### ISSUE THREAD

**Issue by TsSaltan** [jphp-compiler/develnext#180]
Не удаётся получить доступ к протоколу res 
```php
$audio = 'res://.data/ppk.mp3';
$media = new UXMedia($audio); // MediaException: MEDIA_UNAVAILABLE ...
$media = UXMedia::createFromResource($audio); // java.io.IOException: Unable to load resource

ResourceStream::tryAccess($audio, function(){
            // Путь к ресурсному файлу прописан корректно, эта функция успешно выполняется
            var_dump('Resource exists!');
});
```

Проект с ошибкой https://hub.develnext.org/project/uCchFLtUps

**Comment by vova77** [comment]
Прекрасно работает.
public $audio = `'res://.data/ppk.mp3';
Далее так Media::open($this->audio);

**Comment by TsSaltan** [comment]
Я думал по аналогии с UXImage, если там поддерживается res, то почему бы и здесь таким же путем не пойти. Тем не менее, хотя бы метод createFromResource должен работать

**Comment by vova77** [comment]
Эти функции в самом плеере для того чтобы проще было писать , посмотри в исходниках
https://github.com/jphp-compiler/develnext/blob/master/jphp-app-framework/src/script/MediaPlayerScript.php

**Comment by TsSaltan** [comment]
Ага, понял, не дошёл до этого момента в исходниках. Спасибо
