### ISSUE TITLE
Некорректная работа isset() cо свойствами объекта

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#181]
![_rmvfe51tvm](https://user-images.githubusercontent.com/17342159/28084859-a6bdca04-6682-11e7-8d89-4ae84316ac67.jpg)
Условие должно было проходить и в консоле должен был вардампиться стринг 'true', т.к. свойство 'text' некоторых объектов != NULL

**Comment by artemirq** [comment]
Еще хотел бы задать. Думал, куда написать этот вопрос. Вопрос относиться к JPHP, но баг найден благодаря среде. Так куда такие баги заливать?

**Comment by dim-s** [comment]
Это не баг JPHP, это в DN, у класса UXNode скорее всего ошибка в реализации метода __isset().
