### ISSUE TITLE
Странная утечка памяти свойства класса

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#186]
![image](https://user-images.githubusercontent.com/17342159/28323847-9cf527fa-6be2-11e7-8f88-a5357135b26f.png)
![image](https://user-images.githubusercontent.com/17342159/28323917-cbf937f8-6be2-11e7-9129-ba5efa9e1bad.png)
Значение свойства как-будто исчезло, а если использовать не напрямую, а через локальную переменную, то все нормально

**Comment by dim-s** [comment]
Похоже на баг в json расширении jphp.

**Comment by artemirq** [comment]
Странно. Попытался воспроизвести баг в пустом проекте...
![image](https://user-images.githubusercontent.com/17342159/28365061-b002c5a2-6c8f-11e7-9017-332e6d5136f4.png)
Попытаюсь воспроизвести и узнать более конкретные условия воспроизведения бага

**Comment by artemirq** [comment]
@dim-s, нашел зависимость. Дело в комбинации array_merge() + (new JsonProcessor)->format()
![image](https://user-images.githubusercontent.com/17342159/28375904-74c7c1e6-6cb1-11e7-9cc5-38df3b8f549a.png)
