### ISSUE TITLE
Ошибка при запуске в Linux

### ISSUE THREAD

**Issue by MrNexon** [jphp-compiler/develnext#195]
При запуске приложения в linux появляется ошибка
`Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/Parent`
Однако в Windows её нет

**Comment by artemirq** [comment]
sudo apt-get install openjfx

**Comment by artemirq** [comment]
@dim-s, Предлагаю закрыть эту тему, автор неактивен
