### ISSUE TITLE
Баг UXList

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#196]
Создал UXHBox, поместил внутрь две кнопки. Обратился к детям UXHBox, вызвал метод rewind(), а потом current(), который возвратил NULL. С динамическим созданием та же ситуация
![static](https://user-images.githubusercontent.com/17342159/29745642-35222546-8ac9-11e7-9c90-270bfdc9fdd8.png)
![dynamic](https://user-images.githubusercontent.com/17342159/29745666-18af1440-8aca-11e7-9e29-fdf354835631.png)

**Comment by dim-s** [comment]
Оказалось это не баг, т.к. children возвращает каждый раз новую обертку над список со своим итератором. Достаточно поместить children в переменную и все будет работать как ожидалось:

```php
$children = $hbox->children;
$children->rewind();
var_dump($children->current());
```
