### ISSUE TITLE
После закрытия, DN ~40 секунд висит в процессах

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#199]
Смысл бездействовать 40 секунд?
![fantasy2](https://user-images.githubusercontent.com/17342159/30701592-53db08de-9ef3-11e7-822d-62cd990555c9.gif)

**Comment by dim-s** [comment]
Пока хотя бы 1 поток активен в Java приложении, процесс не закроется, через 40 сек. происходит полный exit, если его делать сразу, то легко потерять данные, которые еще не сохранились, либо стороннее расширение для DN в будущем может быть написано аккуратно и держать процесс dn открытым, а в такой схеме оно все равно закроется.
