### ISSUE TITLE
[story203-jfoenix] Невидимое значение в Material Combobox

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#204]
![fantasy](https://user-images.githubusercontent.com/17342159/31089723-caf1fbc2-a7ad-11e7-9d50-105423fe6f34.gif)

При выборе элемента, отображает нормально

**Comment by dim-s** [comment]
комбобокс от material не работает в таком режиме, значение принимается если оно есть в списке, да и все в разработке, все эти баги я вижу.
