### ISSUE TITLE
[story203-jfoenix] Неверный размер Material TextArea в Designer'e

### ISSUE THREAD

**Issue by artemirq** [jphp-compiler/develnext#205]
![fantasy](https://user-images.githubusercontent.com/17342159/31089880-59acbe92-a7ae-11e7-91c7-fe5c0adf2590.gif)

**Как видно, после сборки совсем другой размер**

**Comment by dim-s** [comment]
Все в разработке, эти баги я видел, jfoenix не очень качественно сделанная либа, надо адаптировать редактор к ней.
