### ISSUE TITLE
Ошибка при запуске: timer already cancelled.

### ISSUE THREAD

**Issue by TsSaltan** [jphp-compiler/develnext#214]
При запуске среды возникает ошибка, приходится перезапускать среду

![image](https://user-images.githubusercontent.com/3524731/32559689-d38f1da0-c4b8-11e7-86b5-2f33997baab8.png)

**Comment by dim-s** [comment]
Это вроде как баг Timer из JPHP, вроде пофиксил https://github.com/jphp-compiler/jphp/commit/960523e1a6a3e0a4ac06258da093852ed115c059
