### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by maxgrt** [jphp-compiler/develnext#226]
![1577470172685971860240875589741](https://user-images.githubusercontent.com/38078000/71527611-36349f80-28ed-11ea-8754-03679e1798bd.jpg)

**Comment by TsSaltan** [comment]
Много раз обсуждалось
Надо удалить папку .DevelNext из домашней папки пользователя

**Comment by maxgrt** [comment]
благодарю

________________________________
От: TsSaltan <notifications@github.com>
Отправлено: воскресенье, 29 декабря 2019 г., 13:29
Кому: jphp-group/develnext
Копия: maxgrt; Author
Тема: Re: [jphp-group/develnext] Не запускается (#226)


Много раз обсуждалось
Надо удалить папку .DevelNext из домашней папки пользователя
