### ISSUE TITLE
Редактор кода слетел

### ISSUE THREAD

**Issue by ledjajev** [jphp-compiler/develnext#227]
php\lang\JavaException
java.lang.IndexOutOfBoundsException: 3459 not in [0, 1]

Error in file 'res://ide/editors/CodeEditor.php'
	-> on line 428

#0 {closure}() called at [res://ide/editors/form/IdeEventListPane.php:599]
#1 ide\editors\form\IdeEventListPane->openEventSource() called at [res://ide/editors/form/IdeEventListPane.php:610]
#2 ide\editors\form\IdeEventListPane->openInConstructor() called at [res://ide/editors/form/IdeEventListPane.php:332]
#3 ide\editors\CodeEditor->setValue() called at [res://ide/editors/form/IdeEventListPane.php:400]
#4 php\gui\designer\UXAbstractCodeArea->setText() called at [res://ide/editors/CodeEditor.php:428]
#5 {main}
![image](https://user-images.githubusercontent.com/44301044/75117606-a3f61100-567b-11ea-9119-6897f4ea7697.png)

Эта ошибка уничтожила 2 часа работы
![image](https://user-images.githubusercontent.com/44301044/75117738-d8b69800-567c-11ea-9ee0-6522411c16f1.png)

**Comment by dim-s** [comment]
В это версии DN баги уже не исправляются.
