### ISSUE TITLE
Баг func_get_args

### ISSUE THREAD

**Issue by TsSaltan** [jphp-compiler/develnext#28]
1. Есть функция, в которой используется func_get_args
2. Создаём переменную с массивом (со строками и числами баг не проявляется)
3. Вызываем функцию из п.1, передаём аргументом массив из п.2
4. После этого переменная становится NULL

Код:
```
function doButtonAction(UXEvent $event = null)
	{	
		$a = ['a', 'b', 'c'];
		$this->method($a);
		var_dump($a); // NULL ???
	}

public function method()
	{
		func_get_args();
	}
```

Проект: [http://develnext.org/project/NLByQouFUU](http://develnext.org/project/NLByQouFUU)

**Comment by dim-s** [comment]
Как временное решение можешь использовать конструкцию из php 5.6:

```php
function doButtonAction(UXEvent $event = null)
    {   
        $a = ['a', 'b', 'c'];
        $this->method($a);
        var_dump($a); // NULL ???
    }

public function method(...$args)
    {
    }
```

**Comment by dim-s** [comment]
Исправлено:
https://github.com/jphp-compiler/jphp/pull/233/commits/c7a781beb9810ec539689bb9ee6c4d126e8d17d7
