### ISSUE TITLE
Ubuntu 16.04. Открытие папки после компелации

### ISSUE THREAD

**Issue by tibezh** [jphp-compiler/develnext#53]
1) Открываем программу
2) Создаем проект
3) Добавляем 1 кнопку и вешаем на нее простое событие, например диалоговое окно
4) Запустили проект, проверили - все хорошо
5) Компилируем проект в jar файл, скомпилировался - все хорошо, 
6) После компиляции отображается окно "Сборка завершена" (https://drive.google.com/file/d/0B6NtLvPwvvVVVURfMmlxWEVKaDA/view). Нажимаем на кнопку "Открыть пап..." и тогда все зависает. Приходится принудительно закрывать программу и снова открывать. Сам файл компилируется, все хорошо, но вот только папку не открывает.

**Comment by dim-s** [comment]
Fixed.
