### ISSUE TITLE
Грамматические и орфографические ошибки #1

### ISSUE THREAD

**Issue by dim-s** [jphp-compiler/develnext#59]
https://pp.vk.me/c626726/v626726495/31042/1-pSyYA_DzY.jpg
https://pp.vk.me/c626726/v626726495/31049/6ddvUTQDtx4.jpg
https://pp.vk.me/c636028/v636028960/237a3/GudEwQ0FZ-M.jpg

- В редакторе кода написано "Использовать по-умолчанию", правильно "Использовать по умолчанию".
- "Кнопка-переключатель" пишется через дефис, через дефис, поскольку это приложение.
- В подсказке свойства "Прозрачность" написано "на половину", правильно "наполовину".
- В подсказке свойства "ID" написано "индетификатор", правильно "идентификатор".
- В описании поведения "Зеркальное отражение" написано "с низу", правильно "снизу".
- В описании поведения "Рассеянное свячение (Glow)" написано "свячения" и в заголовке, и в описании, правильно "свечение".
- Про "такскать" уже было сказано.
- В пустом окне модулей написано "Добавьте сюда компонентов для модуля". Так, конечно, тоже правильно, но лучше, если там было бы написано "компоненты".

**Comment by Disquse** [comment]
http://vk.com/photo-98679140_429895007

**Comment by dim-s** [comment]
@Disquse Это уже поправлено в бета5.

**Comment by dim-s** [comment]
:tada:
