### ISSUE TITLE
Несколько предложений/исправлений

### ISSUE THREAD

**Issue by Craftist** [jphp-compiler/develnext#63]
1. Было бы хорошо, если бы при изменении размеров формы значения в редакторе свойств сами бы обновлялись.
2. Стандартный размер формы при запуске - 450 на 450, предлагаю сделать 640*480
3. Все-таки предлагаю сделать пипетку для редактора цвета.
4. В редакторе кода написано "Использовать по-умолчанию", правильно "Использовать по умолчанию".
5. "Кнопка-переключатель" пишется через дефис, через дефис, поскольку это приложение.
6. Предлагаю сделать так, что при перемещении компонента будет появляться подсказка с координатами компонента, как это сделано при ресайзе.
7. В подсказке свойства "Прозрачность" написано "на половину", правильно "наполовину",
8. В подсказке свойства "ID" написано "индетификатор", правильно "идентификатор".
9. В описании поведения "Зеркальное отражение" написано "с низу", правильно "снизу".
10. В описании поведения "Рассеянное свячение (Glow)" написано "свячения" и в заголовке, и в описании, правильно "свечение".
11. Про "такскать" уже было сказано.
12. В пустом окне модулей написано "Добавьте сюда компонентов для модуля". Так, конечно, тоже правильно, но лучше, если там было бы написано "компоненты".
13. В модулях. "Медиа плеер" все-таки лучше написать слитно.
14. Неплохо было бы иметь возможность клонировать формы/скрипты.
15. Все-таки в том редакторе, который в конструкторе, предлагаю оставить код чисто события, как в ДС было. Очень привычно и хорошо было. А сейчас тупо продублировано с основного редактора. Зачем? #ДимаВерниРедакторВКонструктореКакВДС
16. Предлагаю добавить чатик в саму среду, чтобы можно было там задавать вопросы. Естественно, чтобы общаться, надо войти в свой аккаунт.
17. Если среда уже открыта, то ссылка develnext://project:blablabla должна предлагать открывать проект уже в существующем процессе среды, а не открывать новый.

Возможно будет дополнено.

**Comment by Disquse** [comment]
16-ый номер, к слову, очень хорошая идея. Сделать общий чат для Девелнекст юзеров, где все люди могли бы общаться между собой. Конечно, есть группа, но чат все-таки был бы удобнее и быстрее.

**Comment by dim-s** [comment]
@Disquse 16 номер, да я такое уже давно хочу запилить.

**Comment by dim-s** [comment]
Спасибо за отчет. Я закрою issue, все что нужно потом отдельно заведу.
