### ISSUE TITLE
Стандартные функции, такие как base64_decode, md5,

### ISSUE THREAD

**Issue by yanislavb** [jphp-compiler/develnext#9]
Как их использовать здесь?

**Comment by dim-s** [comment]
Они есть в дополнительном расширении, которое пока не подключено к среде. Ждите, скоро будет.

**Comment by yanislavb** [comment]
К сожалению, вынужден поднять тред. Когда они будут прикреплены?

**Comment by dim-s** [comment]
Их уже можно использовать в последней сборке.
