### ISSUE TITLE
Исчезает содержимое массива

### ISSUE THREAD

**Issue by TsSaltan** [jphp-compiler/develnext#92]
```php
public function arr($array){
        var_dump($array);
        $this->isArray($array);
        var_dump($array);
    }
    
public function isArray($array){        
     $array = is_array($array);
     // $array = isset($array[0]); // то же самое и с isset
 }
```
При вызове $this->arr(['abc' => 'def', 123 => 456]); ожидается, что дважды будет выведен дамп одного и того же массива, но в результате 2й раз выводится пустой массив

```
array(2) {
  ["abc"]=>
  string(3) "def"
  [123]=>
  int(456)
}
array(0) {
}
```

Проект http://develnext.org/project/SsYMValQeN

p.s. уже очень давно бесит этот баг, но только сейчас получилось найти минимальный код, который его вызывает

**Comment by dim-s** [comment]
Ок, да, спасибо за короткий код воспроизведения. Посмотрим в чем тут дело.

**Comment by dim-s** [comment]
Исправлено:
https://github.com/jphp-compiler/jphp/commit/8b437e0825eec8c9f3c1c1ab7375b0801ea03112

Возможно и другие проблемные места с массивами будут исправлены.
