### ISSUE TITLE
Не компилируется в байт-код файл .bootstrap

### ISSUE THREAD

**Issue by TsSaltan** [jphp-compiler/develnext#94]
Если файлу добавить расширение .php и в конфиге **launcher.conf** изменить пути
```
bootstrap.file = JPHP-INF/.bootstrap.phb
```
то всё скомпилируется и успешно запустится

Не очень хорошо, что ресурсы и конфиги открыты и доступны для редактирования. В том же launcher.conf можно прописать пусть к другому файлу, и в уже собранной программе запустить произвольный код

**Comment by dim-s** [comment]
@TsSaltan  Есть еще миллион способов запустить произвольный код, ничто не мешает скомпилировать другой phb файл и поменять его.

**Comment by TsSaltan** [comment]
Значит о серьезной защите можно забыть, жаль
Может как-то можно проверять целостность содержимого?

**Comment by dim-s** [comment]
@TsSaltan Многие вирусы с легкостью добавляются к другим exe файлам, никакой проверки целостности у многих программ не имеется, даже если они нативно скомпилированы. Это конечно можно сделать, но кому надо, найдет как обойти ее.
