### ISSUE TITLE
При перетаскивании компонента с палитры на форму возникает ошибка

### ISSUE THREAD

**Issue by namonexarap** [jphp-compiler/develnext#99]
php\lang\IllegalArgumentException
The node must have parent value

Ошибка в файле 'res://php/gui/framework/DataUtils.php'
	-> на строке 180

#0 {closure}() called at [res://ide/editors/FormEditor.php:933]
#1 ide\editors\FormEditor->createElement() called at [res://ide/editors/FormEditor.php:1707]
#2 ide\editors\FormEditor->registerNode() called at [res://ide/editors/FormEditor.php:2049]
#3 ide\formats\form\elements\LabeledFormElement->registerNode() called at [res://ide/editors/FormEditor.php:967]
#4 php\gui\framework\DataUtils::get() called at [res://ide/formats/form/elements/LabeledFormElement.php:43]
#5 {main}

**Comment by dim-s** [comment]
Исправлено в 16.5.1
